import Head from 'next/head'
import styles from '@/styles/Home.module.scss';
import HeroBanner from '@/components/hero-banner';
import NavBar from '@/components/nav-bar';
import React,{ useLayoutEffect} from 'react';
import { mouseFollower, makeMagnet, hoverWithMediaCircle } from '@/utils/effects';
import Featured from '@/components/featured';

let loaded = false;

export default function Home() {

  useLayoutEffect(()=>{
    if(!loaded){
      console.log("hi2")
      mouseFollower();
      makeMagnet('.magnet')
      hoverWithMediaCircle(".hvr", {
        videos: ["/videos/0.mp4", "/videos/2.mp4", "/videos/3.mp4"],
      });
    }
    loaded = true;
  },[]) 

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main className={`${styles.main}`} id='main'>
        <NavBar/>
        <HeroBanner/>
        <Featured/>
      </main>
    </>
  )
}



